#! /usr/bin/php -f
<?php

require_once(dirname(__FILE__) . '/palette.php');
require_once(dirname(__FILE__) . '/lib/svggenerator.php');

$stdout = fopen('php://stdout', 'w');
$stderr = fopen('php://stderr', 'w');
if(count($argv) < 3 || count($argv) > 5)
{
	fprintf($stderr, "Usage: %s WIDTH HEIGHT [COLOUR] [TRIANGLE-SIZE] > file.svg\n", $argv[0]);
	exit(1);
}

$width = intval($argv[1]);
$height = intval($argv[2]);
if(count($argv) >= 4)
{
	if(!isset($palette[$argv[3]]))
	{
		fprintf($stderr, "%s: colour palette '%s' is not supported\n", $argv[0], $argv[3]);
		exit(1);
	}
	$colours = $palette[$argv[3]];
}
else
{
	$colours = $palette['blue'];
}
if(count($argv) >= 5)
{
	$size = intval($argv[4]);
}
else
{
	$size = 32;
}

$generator = new SVGGenerator();
$generator->palette->set($colours);
$generator->setDimensions($width, $height);
$generator->setSize($size);
$generator->generate($stdout);
