#! /bin/sh

here=`pwd`

# This can be changed to an absolute path, e.g., if there's an installed
# version (in which case, it might be, for example,
# /usr/lib/triangle-background-generator)

deflib="$here"

case "$0" in
	*/*)
		reldir=`dirname "$0"`
		cd "$reldir"
		if test -d lib && test -f lib/cli.php ; then
			libdir="`pwd`/lib"
		else
			libdir="$deflib"
		fi
		;;
	*)
		libdir="$deflib"
esac

if test -f "$libdir/cli.php" ; then
	exec php -f "$libdir/cli.php" -- "$@"
else
	echo "$0: cannot locate $libdir/cli.php" >&2
	exit 1
fi
